"""行程计划数据: 当前计划 + 3 个优化版本.

分数为分析师对照 trip_evaluator.DIMENSIONS 量表给出, 每个分数必附 note 说明依据.
1=很差 2=差 3=及格偏下 4=及格偏上 5=好 6=优秀.
"""

PLANS = {
    "current": {
        "name": "current",
        "label": "当前计划",
        "days": [
            {
                "date": "9/30", "title": "A版: EVE取车→Svolvær→Henningsvær→Hamnøy日落→Lyngvær",
                "scores": {"time": 3, "route": 4, "pace": 3, "light": 5, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "驾驶约5.5h, 一天排满; 午饭Nihao周三14:00才开门, 13:30到需等",
                    "route": "一路向西单向, 但Hamnøy→Lyngvær约100km折返",
                    "pace": "出来第7天+早班机+长驾驶日, 偏累",
                    "light": "卡18:34日落金色时刻在Hamnøy; 云57%, 不给满分",
                    "booking": "RAV4双边一对一实锤, Airbnb门锁码到手, 已加日历",
                    "cost": "今日无异常消费",
                    "risk": "无硬伤; 午饭等半小时+多云看不到日落是已知隐忧",
                    "work": "无会; 美股15:30-22:00正好在开车, 无法盯盘",
                },
                "fields": {"drive_hours": 5.5, "backtrack_km": 100,
                           "lunch_risk": "Nihao周三14:00开门", "consecutive_long_days": 2},
            },
            {
                "date": "10/1", "title": "罗弗敦西线: Hamnøy/Sakrisøy/Reine, Reinebringen可选",
                "scores": {"time": 4, "route": 4, "pace": 4, "light": 5, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "Lyngvær↔Reine各约1.5h, 全天灵活",
                    "route": "以Lyngvær为基地往返, 可接受",
                    "pace": "Reinebringen可选, 可进可退",
                    "light": "晚上20:00-23:30极光窗口已留",
                    "booking": "连住, 无新增订单",
                    "cost": "无异常",
                    "risk": "极光/爬山都看天气, 有备选",
                    "work": "无会",
                },
                "fields": {"drive_hours": 3.5, "backtrack_km": 150},
            },
            {
                "date": "10/2", "title": "转场: 还RAV4→飞Tromsø→取V90",
                "scores": {"time": 3, "route": 5, "pace": 4, "light": 3, "booking": 3, "cost": 5, "risk": 3, "work": 5},
                "notes": {
                    "time": "还车14:30→起飞15:40仅70分钟buffer, 偏紧",
                    "route": "Lyngvær→Leknes→飞→Tromsø, 单向干净",
                    "pace": "转场日, 强度中等",
                    "light": "转场日无光线安排",
                    "booking": "WF816未实时核票; Tromsø入住方式未知",
                    "cost": "无异常",
                    "risk": "紧张转场+两个未核实项",
                    "work": "09:00-11:00两个会开完再出发, 不冲突",
                },
                "fields": {"drive_hours": 1.5,
                           "tight_connections": ["还车14:30→WF816起飞15:40"],
                           "unticketed": ["WF816未实时核票"], "entry_unknown": True},
            },
            {
                "date": "10/3", "title": "Tromsø市区: 大教堂/Fjellheisen/Storsteinen, 晚极光",
                "scores": {"time": 5, "route": 5, "pace": 5, "light": 5, "booking": 4, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "市区日, 时间充裕",
                    "route": "本地活动, 无长途",
                    "pace": "休息节奏",
                    "light": "晚上极光窗口",
                    "booking": "Tromsø入住方式仍未知 (延续10/2)",
                    "cost": "无异常",
                    "risk": "低风险日",
                    "work": "仅07:00-07:30一个会",
                },
                "fields": {"entry_unknown": True},
            },
            {
                "date": "10/4", "title": "待定 (Senja已否, 替换方案未定)",
                "scores": {"time": 2, "route": 2, "pace": 3, "light": 3, "booking": 4, "cost": 5, "risk": 2, "work": 4},
                "notes": {
                    "time": "无计划=时间账没法算",
                    "route": "无计划=路线账没法算",
                    "pace": "未定, 中性",
                    "light": "未定, 中性",
                    "booking": "V90在手, 无新增需求",
                    "cost": "无异常",
                    "risk": "待定的一天本身就是风险",
                    "work": "Dennis 30分钟会还没约",
                },
                "fields": {"unticketed": ["10/4行程待定"]},
            },
            {
                "date": "10/5", "title": "南下: TOS→OSL→取Macan→Stange/Mjøsa",
                "scores": {"time": 3, "route": 5, "pace": 4, "light": 3, "booking": 2, "cost": 5, "risk": 3, "work": 5},
                "notes": {
                    "time": "飞+取车+开车挤在一天, 偏紧",
                    "route": "一路向南, 干净",
                    "pace": "中等",
                    "light": "转场日无光线安排",
                    "booking": "TOS→OSL仅候选未出票; Konglehytta门禁码待临近发送",
                    "cost": "无异常",
                    "risk": "未出票的航班是最大风险点",
                    "work": "无会",
                },
                "fields": {"unticketed": ["TOS→OSL 10:45-12:40仅候选未出票", "Konglehytta门禁待发"],
                           "tight_connections": ["12:40落地→13:00取Macan"]},
            },
            {
                "date": "10/6", "title": "还Macan, DY1406飞Nice",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "还车+飞, 17:20起飞不赶",
                    "route": "干净",
                    "pace": "中等",
                    "light": "转场日",
                    "booking": "DY1406已出票; Nice lockbox已确认",
                    "cost": "无异常",
                    "risk": "低; 上午开完会再收拾行李",
                    "work": "09:00-11:00两个会, 然后赶飞机, 可行",
                },
                "fields": {"drive_hours": 1},
            },
        ],
    },
    "chill": {
        "name": "chill",
        "label": "A·体力优先",
        "days": [
            {
                "date": "9/30", "title": "同当前 (已执行)",
                "scores": {"time": 3, "route": 4, "pace": 3, "light": 5, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前: 5.5h驾驶日已定",
                    "route": "同当前",
                    "pace": "同当前: 今天累, 后面补回来",
                    "light": "同当前",
                    "booking": "同当前",
                    "cost": "同当前",
                    "risk": "同当前",
                    "work": "同当前",
                },
                "fields": {"drive_hours": 5.5, "backtrack_km": 100},
            },
            {
                "date": "10/1", "title": "慢西线: 去掉Reinebringen, 早回桑拿回血",
                "scores": {"time": 5, "route": 4, "pace": 6, "light": 4, "booking": 5, "cost": 5, "risk": 5, "work": 5},
                "notes": {
                    "time": "砍掉爬山, 时间一下松了",
                    "route": "同当前",
                    "pace": "度假模式: 睡醒出发+下午桑拿",
                    "light": "极光改在lodge门口看, 少跑路",
                    "booking": "连住无新增",
                    "cost": "无异常",
                    "risk": "无高强度项, 风险最低",
                    "work": "无会",
                },
                "fields": {"drive_hours": 3},
            },
            {
                "date": "10/2", "title": "转场+提前到Leknes(13:30), 出发前核WF816",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 4, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "提前1小时到机场, buffer拉长",
                    "route": "同当前",
                    "pace": "同当前",
                    "light": "同当前",
                    "booking": "WF816出发前实时核实, 去掉一个未知",
                    "cost": "无异常",
                    "risk": "buffer+核实, 风险降一档",
                    "work": "同当前",
                },
                "fields": {"drive_hours": 1.5,
                           "tight_connections": ["还车14:30→起飞15:40 (提前到机场)"]},
            },
            {
                "date": "10/3", "title": "Tromsø慢市区+10/1晚已拿入住方式",
                "scores": {"time": 5, "route": 5, "pace": 6, "light": 5, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "市区日从容",
                    "route": "本地",
                    "pace": "Fjellheisen坐缆车不爬山, 纯休息",
                    "light": "晚上极光",
                    "booking": "10/1晚上已找房东拿入住方式",
                    "cost": "无异常",
                    "risk": "低",
                    "work": "仅早会",
                },
                "fields": {},
            },
            {
                "date": "10/4", "title": "Chill本地: Ersfjordbotn/Kvaløya+市区+极光",
                "scores": {"time": 5, "route": 5, "pace": 6, "light": 5, "booking": 5, "cost": 5, "risk": 5, "work": 5},
                "notes": {
                    "time": "100km内, 时间大把",
                    "route": "Tromsø周边, 无折返",
                    "pace": "全程最松的一天",
                    "light": "Ersfjordbotn日落+晚上极光",
                    "booking": "无新增需求",
                    "cost": "无异常",
                    "risk": "本地活动, 天气不好随时回城",
                    "work": "Dennis会可约在这天上午",
                },
                "fields": {"drive_hours": 1.5},
            },
            {
                "date": "10/5", "title": "南下 (航班已提前出票)",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "出票后心里踏实, 时间同当前",
                    "route": "同当前",
                    "pace": "同当前",
                    "light": "同当前",
                    "booking": "TOS→OSL提前出票, 只剩Konglehytta门禁待发",
                    "cost": "无异常",
                    "risk": "航班落定, 风险降档",
                    "work": "无会",
                },
                "fields": {},
            },
            {
                "date": "10/6", "title": "同当前",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前", "booking": "同当前", "cost": "同当前",
                    "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 1},
            },
        ],
    },
    "max": {
        "name": "max",
        "label": "B·体验拉满",
        "days": [
            {
                "date": "9/30", "title": "同当前 (已执行)",
                "scores": {"time": 3, "route": 4, "pace": 3, "light": 5, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前", "booking": "同当前", "cost": "同当前",
                    "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 5.5, "backtrack_km": 100},
            },
            {
                "date": "10/1", "title": "全西线+Reinebringen+开车追极光",
                "scores": {"time": 3, "route": 4, "pace": 3, "light": 6, "booking": 5, "cost": 5, "risk": 3, "work": 5},
                "notes": {
                    "time": "爬山+追极光, 一天排满",
                    "route": "同当前",
                    "pace": "连续第2天高强度",
                    "light": "日落+极光追拍拉满",
                    "booking": "连住无新增",
                    "cost": "无异常",
                    "risk": "爬山看天气, 夜间开车追极光",
                    "work": "无会",
                },
                "fields": {"drive_hours": 4, "backtrack_km": 150, "consecutive_long_days": 3},
            },
            {
                "date": "10/2", "title": "同当前转场",
                "scores": {"time": 3, "route": 5, "pace": 4, "light": 3, "booking": 3, "cost": 5, "risk": 3, "work": 5},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "转场日回血",
                    "light": "同当前", "booking": "同当前: WF816未核+Tromsø入住未知",
                    "cost": "同当前", "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 1.5,
                           "tight_connections": ["还车14:30→起飞15:40"],
                           "unticketed": ["WF816未实时核票"], "entry_unknown": True},
            },
            {
                "date": "10/3", "title": "Tromsø市区+夜间开车追极光",
                "scores": {"time": 4, "route": 4, "pace": 4, "light": 6, "booking": 5, "cost": 5, "risk": 3, "work": 5},
                "notes": {
                    "time": "白天市区+晚上追极光, 紧凑",
                    "route": "夜间追极光有绕行",
                    "pace": "晚睡, 次日10/4是Sommarøy",
                    "light": "市区日落+深夜极光双杀",
                    "booking": "10/2落地后已拿入住方式",
                    "cost": "无异常",
                    "risk": "深夜开车+疲劳叠加",
                    "work": "仅早会",
                },
                "fields": {"drive_hours": 2},
            },
            {
                "date": "10/4", "title": "Sommarøy+Ersfjordbotn日落",
                "scores": {"time": 4, "route": 4, "pace": 4, "light": 6, "booking": 5, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "单程1h, 一天刚好",
                    "route": "Sommarøy往返+Ersfjordbotn顺路",
                    "pace": "中等, 前一晚追极光有影响",
                    "light": "海滩日落+极光, 光线拉满",
                    "booking": "无新增",
                    "cost": "无异常",
                    "risk": "天气决定体验上限",
                    "work": "Dennis会改约10/1或10/3",
                },
                "fields": {"drive_hours": 3, "backtrack_km": 120},
            },
            {
                "date": "10/5", "title": "南下 (航班已提前出票)",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "同A", "route": "同A", "pace": "同A", "light": "同A",
                    "booking": "提前出票", "cost": "无异常", "risk": "航班落定", "work": "无会",
                },
                "fields": {},
            },
            {
                "date": "10/6", "title": "同当前",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前", "booking": "同当前", "cost": "同当前",
                    "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 1},
            },
        ],
    },
    "safe": {
        "name": "safe",
        "label": "C·稳妥优先",
        "days": [
            {
                "date": "9/30", "title": "同当前 (已执行)",
                "scores": {"time": 3, "route": 4, "pace": 3, "light": 5, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前", "booking": "同当前", "cost": "同当前",
                    "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 5.5, "backtrack_km": 100},
            },
            {
                "date": "10/1", "title": "西线+晚上给Tromsø房东拿入住方式",
                "scores": {"time": 4, "route": 4, "pace": 4, "light": 5, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前",
                    "booking": "当晚消息房东, 10/2落地前入住方式到手",
                    "cost": "无异常", "risk": "同当前", "work": "无会",
                },
                "fields": {"drive_hours": 3.5, "backtrack_km": 150},
            },
            {
                "date": "10/2", "title": "转场: WF816已核实+13:30到Leknes",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 5, "cost": 5, "risk": 4, "work": 5},
                "notes": {
                    "time": "提前到机场, buffer充足",
                    "route": "同当前", "pace": "同当前", "light": "同当前",
                    "booking": "WF816已核实+Tromsø入住方式在手",
                    "cost": "无异常",
                    "risk": "两个未知都消掉",
                    "work": "同当前",
                },
                "fields": {"drive_hours": 1.5},
            },
            {
                "date": "10/3", "title": "Tromsø市区 (入住方式已在手)",
                "scores": {"time": 5, "route": 5, "pace": 5, "light": 5, "booking": 5, "cost": 5, "risk": 5, "work": 5},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前",
                    "booking": "入住方式已提前拿到",
                    "cost": "无异常",
                    "risk": "无未知项, 当天零风险",
                    "work": "仅早会",
                },
                "fields": {},
            },
            {
                "date": "10/4", "title": "Chill本地 (低风险选项)",
                "scores": {"time": 5, "route": 5, "pace": 6, "light": 5, "booking": 5, "cost": 5, "risk": 5, "work": 5},
                "notes": {
                    "time": "100km内", "route": "无折返", "pace": "最松",
                    "light": "日落+极光", "booking": "无新增", "cost": "无异常",
                    "risk": "本地活动随时可撤", "work": "Dennis会可约上午",
                },
                "fields": {"drive_hours": 1.5},
            },
            {
                "date": "10/5", "title": "南下 (航班已出票+Konglehytta已确认)",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 5, "cost": 5, "risk": 5, "work": 5},
                "notes": {
                    "time": "同A", "route": "同A", "pace": "同A", "light": "同A",
                    "booking": "出票+门禁确认, 全齐",
                    "cost": "无异常",
                    "risk": "无未定项",
                    "work": "无会",
                },
                "fields": {},
            },
            {
                "date": "10/6", "title": "同当前",
                "scores": {"time": 4, "route": 5, "pace": 4, "light": 3, "booking": 6, "cost": 5, "risk": 4, "work": 4},
                "notes": {
                    "time": "同当前", "route": "同当前", "pace": "同当前",
                    "light": "同当前", "booking": "同当前", "cost": "同当前",
                    "risk": "同当前", "work": "同当前",
                },
                "fields": {"drive_hours": 1},
            },
        ],
    },
}
